### ISSUE TITLE
HU009 Diagrama de clases

### ISSUE THREAD

**Issue by Cocom1n** [Cocom1n/TPGrupal_PMyDJ#10]
**Descripción**
**Como** desarrollador **quiero** tener un diagrama de clases **para** poder organizarnos mejor a la hora de programar

**Criterios de aceptación**

- [x] Todas las clases del diagrama se ven reflejadas en el proyecto
- [x] Las clases están bien ordenadas y completas
- [x] Las relaciones están definidas correctamente

**Comment by Joaset** [comment]
![Image](https://github.com/Cocom1n/TPGrupal_PMyDJ/assets/143660884/560fe17c-7125-4043-b508-f5d668b03ea4)

30/06 se dibujan todas las clases con sus atributos y métodos y las relaciones de herencia y agregación
